### PR TITLE
Add Glass Doors

### PR DESCRIPTION
**Pull request by tomasdev**
Added sliding glass doors white and brown, and also three regular doors mostly made out of glass: red, black and black with a crossing bar.

### CODE REVIEW

**Comment by tomasdev** [comment]
Fixes #12

**Comment by ProjectSky** [comment]
awesome, my plan to add more stuff, but so busy with work lately, I don't have time to update this mod, thanks for your contribution

**Comment by tomasdev** [comment]
Will it be available soon in Steam?

**Comment by ProjectSky** [comment]
> Will it be available soon in Steam?

yes i will push it today

**Pull request merged**
